name: dk_app_flutter
version: 1.0.0+5
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.12.0 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  hexcolor: ^2.0.4
  syncfusion_flutter_sliders: ^19.2.56
  # flutter_unity_widget: ^2022.1.1+3
  flutter_launcher_icons: ^0.11.0
  get: 4.6.1
  get_storage: 2.0.3
  intro_slider: 3.0.3
  intl: 0.17.0
  video_player: 2.2.19
  chewie: 1.3.0
  dart_numerics: 0.0.6
  flutter_keyboard_visibility: 5.2.0
  camera: ^0.9.7
  google_mlkit_commons: ^0.2.0
  google_mlkit_face_detection: ^0.3.0
  url_launcher: ^6.1.2
  collection: ^1.16.0
  carousel_slider: 4.1.1
  svg_path_parser: 1.1.1
  touchable: 1.0.2
  flutter_svg: 1.1.1+1
  flutter_easyloading: 3.0.5
  blobs: 
    path: ./flutter_blobs
  flutter: 
    sdk: flutter
  # firebase_core: ^2.8.0
  awesome_notifications_fcm: ^0.7.3
  # firebase_messaging: ^14.3.0
  connectivity_plus: ^2.3.9
  shared_preferences: ^2.0.15
  flutter_html: ^3.0.0-alpha.6
  health: ^4.1.1
  permission_handler: ^10.2.0
  

dev_dependencies: 
  flutter_lints: ^1.0.0
  logger: 1.1.0
  image: ^3.2.0

flutter: 
  assets: 
    - assets/images/
    - assets/images/inventory/
    - assets/video/
    - assets/tf/
  fonts: 
    - family: Righteous
      fonts: 
        - asset: fonts/Righteous-Regular.ttf
  uses-material-design: true

flutter_icons: 
  android: "launcher_icon"
  image_path: assets/icon/icon.png
  ios: true
  remove_alpha_ios: true

