// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCYLSw8awT3Gtmm9nus5chp57bA69-r3qY',
    appId: '1:861597823617:web:f2cb8ee921c1aa7df69380',
    messagingSenderId: '861597823617',
    projectId: 'dkapp-ec8a8',
    authDomain: 'dkapp-ec8a8.firebaseapp.com',
    storageBucket: 'dkapp-ec8a8.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDTvTCYIxqR5_Q8c9QTEfvX-9LwIUN4uJU',
    appId: '1:861597823617:android:9c389ed58023527df69380',
    messagingSenderId: '861597823617',
    projectId: 'dkapp-ec8a8',
    storageBucket: 'dkapp-ec8a8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBA_Pj9UUCIifgCjQ0QyH02NVF-SjGlzv8',
    appId: '1:861597823617:ios:29e7c6add7274652f69380',
    messagingSenderId: '861597823617',
    projectId: 'dkapp-ec8a8',
    storageBucket: 'dkapp-ec8a8.appspot.com',
    iosClientId: '861597823617-o3dd9kni6p1nibmcu5pp5k0ilejbdjgj.apps.googleusercontent.com',
    iosBundleId: 'com.dkDemoV1.personal',
  );
}
